export const BASE_URL = import.meta.env.VITE_APP_BASE_URL;

export const END_POINT = {
  FETCH_MY_PAGE: "/users",
  POST_TOKEN_REISSUE: "/auth/token-reissue",
  POST_SIGNUP: "/users/profile",
  FETCH_USER_PROFILE: "/users/profile",
  PATCH_USER_PROFILE: "/users/profile",
  FETCH_FRIEND_LIST: "/friends",
  POST_FOLLOW: "/friends",
  FETCH_FRIEND_CODE: "/friends",
  FETCH_FRIEND_SEARCH: "/friends/search",
  DELETE_UNFOLLOW: (friendId: number) => `/friends/${friendId}`,
  POST_RECORD: "/records",
  FETCH_RECORD_LIST: "/records",
  FETCH_RECORD_DETAIL: (recordId: number) => `/records/${recordId}`,
  PUT_RECORD: (recordId: number) => `/records/${recordId}`,
  DELETE_RECORD: (recordId: number) => `/records/${recordId}`,
  FETCH_RECORD_SEARCH: "/records/search",
  FETCH_CATEGORIES: "/categories",
  POST_CATEGORY: "/categories",
  PUT_CATEGORY: (categoryId: number) => `/categories/${categoryId}`,
  FETCH_ALARM_LIST: "/notifications",
  FETCH_QUIZ_LIST: "/quizzes",
  FETCH_QUIZ_DETAIL: (quizId: number) => `/quizzes/${quizId}`,
  POST_QUIZ: (recordId: number) => `/quizzes/${recordId}`,
  PATCH_BACKGROUND: "/users/background",
  FETCH_USER_MAIN: "/main",
  FETCH_USER_STREAK: "/streak",
  FETCH_OTHER_MAIN: "/main",
  FETCH_OTHER_STREAK: "/streak",
};
